[module]
name = "ABM8_272_T3"
entry = "ABM8272T3.ato:ABM8272T3"
description = "Crystal, 12 MHz, SMD, 3.2mm x 2.5mm, 30 ppm, 10 pF, 30 ppm, ABM8 Series"
datasheet = "https://abracon.com/datasheets/ABM8-272-T3.pdf"

[registries]
diodelib = { url = "git@github.com:dioderobot/diodelib.git", rev = "main" }

[dependencies]
generics = { path = "generics", registry = "diodelib" }
